### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by SiNaPsEr0x** [gottburgm/wpFlak#1]
on kali 2018
Can't locate lib/Requester.pm in @INC (you may need to install the lib::Requester module) (@INC contains: lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.2 /usr/local/share/perl/5.26.2 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at wpflak.pl line 18.
BEGIN failed--compilation aborted at wpflak.pl line 18.

**Comment by gottburgm** [comment]
Weird, it seems that you are running it from another directory.

Please try the following command:

git clone https://github.com/gottburgm/wpFlak/
cd wpFlak
perl wpflak.pl -u http://127.0.0.1/

In fact you have to run the script from the directory inside which it is located
